build: off
environment:
  # global:
  #   WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: 'py27'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'

    - TOXENV: 'py27'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'

    - TOXENV: 'py34'
      TOXPYTHON: C:\Python34\python.exe
      PYTHON_HOME: C:\Python34
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '32'

    - TOXENV: 'py34'
      TOXPYTHON: C:\Python34-x64\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\Python34-x64
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '64'

    - TOXENV: 'py35'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'

    - TOXENV: 'py35'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'

    # Python 3.6 fails with: "Failed to build cryptography"
    # - TOXENV: 'py36'
    #   TOXPYTHON: C:\Python36\python.exe
    #   PYTHON_HOME: C:\Python36
    #   PYTHON_VERSION: '3.6'
    #   PYTHON_ARCH: '32'
    #
    # - TOXENV: 'py36'
    #   TOXPYTHON: C:\Python36-x64\python.exe
    #   PYTHON_HOME: C:\Python36-x64
    #   PYTHON_VERSION: '3.6'
    #   PYTHON_ARCH: '64'

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\pip install -U tox'
  - '%PYTHON_HOME%\Scripts\tox --version'

test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
